services:
  qwen-proxy:
    build: .
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      # You can set your Qwen credentials here or use a .env file
      # - QWEN_CLIENT_ID=your_client_id
      # - QWEN_CLIENT_SECRET=your_client_secret
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"